OutMyVoice/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin Site URL(s)
    path('admin/', 
        admin.site.urls
    ),
    
    # User App (mysite) URL(s)
    url(r'', 
        include('mysite.urls')
    ),
    
    # CK Editor URL(s)
    path('ckeditor/', 
        include('ckeditor_uploader.urls')
    ),
    
    # Blog App URL(s)
    path('blog/',
        include('blogs.urls')
    ),
]


if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


urlpatterns = [
    
    # Blog List View URL
    url(r'^$',
        views.BlogList,
        name='list'
    ),
    
    # Blog Post Detail View URL
    url(r'^detail/(?P<slug>[-\w]+)$',
        views.BlogDetail,
        name='detail'
    ),
    
    # Blog Search View URL
    url(r'^search/',
        views.search,
        name='search'
    ),
    
    # BLog Post Form View URL
    url(r'^create-a-blog/',
        views.blogFormView,
        name='blog'
    ),
    
    # Blog Comment Reply View URL
    url(r'^reply/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.ReplyPage,
        name='reply'
    ),
    
    # Self Blogs 
    url(r'^self-blogs/$', views.self_Blogs, name="self_blogs_url"),
    
    # Editing BLog
    path('edit-blog/<int:blog_id>', views.blogFormViewEditing, name="blog_editing"),
    
    
    # ****************************************************************
    # Assign a blog by a global admin
    # ****************************************************************
    path("assign-a-blog", views.AssignBlog, name="Assign"),
    
    
    # ****************************************************************
    # Approve Current Publish Project
    # ****************************************************************
    path("approve-blog/<int:blog_id>/", views.Approve, name="Approve"),
    
    
        
    # ****************************************************************
    # Disapprove Current Publish Project
    # ****************************************************************
    path("disapprove-blog/<int:blog_id>/", views.Disapprove, name="Disapprove"),


]

blogs/models.py
from django.db import models
from django.conf import settings
from embed_video.fields import EmbedVideoField
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.conf import settings
from django.core.mail import send_mail
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse

class Blog(models.Model):
    author      =       models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=False)
    title       =       models.CharField(max_length=1000 , blank=False)
    slug        =       models.CharField(max_length=1000, blank=False)
    image       =       models.ImageField(blank=True)
    video       =       EmbedVideoField(blank=True)
    description =       RichTextUploadingField( blank=True)
    created_at  =       models.DateTimeField(auto_now_add=True)
    updated     =       models.DateTimeField(auto_now=True)
    publish     =       models.BooleanField(blank=True,default=None, null=True)
    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("detail", args=[self.slug])
        
        
class BlogComment(models.Model):
    name        =       models.CharField(max_length=100)
    email       =       models.CharField(max_length=100)
    description =       models.TextField(max_length=1000)
    post_date   =       models.DateTimeField(auto_now_add=True)
    blog        =       models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-post_date"]

    def __str__(self):
        return self.description
    
  



class BlogReply(models.Model):
    name        =       models.CharField(max_length=100)
    email       =       models.CharField(max_length=100)
    description =       models.TextField(max_length=1000)
    post_date   =       models.DateTimeField(auto_now_add=True)
    comment     =       models.ForeignKey(BlogComment, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-post_date"]

    def __str__(self):
        return self.name

blogs/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class Comment(ModelForm):
    class Meta:
        model = BlogComment
        fields =  [
            'name',     
            'email',       
            'description',         
             
    
        ]

class Reply(ModelForm):
    class Meta:
        model = BlogReply
        fields =  [
            'name',     
            'email',       
            'description',         
]


class blogform(ModelForm):
    class Meta:
        model=Blog
        exclude = ['author','slug','publish']
        
        
class AssignBlogForm(ModelForm):
    class Meta:
        model = Blog
        exclude = [
            'slug',
            'publish'
        ]

blogs/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.core.mail import send_mail
from .tokens import account_activation_token
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.defaultfilters import slugify
from django.contrib.auth.decorators import login_required
from mysite.models import *
from django.contrib import messages






# Blog Post List View
def BlogList(request):
    if request.user.is_authenticated:
        try:
            profile = UserProfile.objects.get(user = User.objects.get(username = request.user.username))
            if request.user.is_superuser or profile.golbal_Admin == "True":
                blog = Blog.objects.all()
            else:
                blog = Blog.objects.filter(publish = True)
        except :
            profile = None
            blog = Blog.objects.filter(publish = True)
    else:
        profile = None
        blog = Blog.objects.filter(publish = True)
    paginator = Paginator(blog ,10, allow_empty_first_page=True)
    page = request.GET.get('page', 1)
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage :
        blogs = paginator.page(paginator.num_pages)
    context = {
        'blogs':blogs,
        'blog':blog,
        'blog_all_section': True,
        'paginator': paginator,
        'profile':profile
    }
    return render(request,'blog-list-sidebar.html',context)


# Blog Post Detail View
def BlogDetail(request,slug):
    try:
        blogs = Blog.objects.get(slug = slug)
        if request.user.is_authenticated:
            try:
                profile = UserProfile.objects.get(user = User.objects.get(username = request.user.username))
            except:
                profile  = None
            if request.user.is_superuser or profile.golbal_Admin == "True" or  blogs.author ==  User.objects.get(username = request.user.username) :
                blogs = Blog.objects.get(slug=slug)
            else:
                return redirect(reverse("list"))
        else:
            if blogs.publish is not True:
                messages.success(request, "Invalid Request")
                return redirect(reverse("list"))        
        comments= BlogComment.objects.filter(blog=blogs)
        # reply = BlogReply.objects.filter(comment = comments)    
        # print(reply)
        replies = BlogReply.objects.all()
        # print(comments)
        form = Comment()
        form_1 = Reply()
        if request.method =='POST':
            form=Comment(request.POST or None)
            if form.is_valid():
                new_comment = form.save(commit=False)
                new_comment.blog=blogs
                new_comment.save()
                form.save()
                return HttpResponseRedirect(reverse('detail', args=[slug]))
        context = {
        'blogs':blogs,
        'comments':comments,
        'list':None,
        'form':form,
        # 'relpy' : reply,
        'replies' : replies,
        'form_1' : form_1,
        # 'blog_all_section':True
        "blog_detail_section":True,
        'profile': profile
        }
        return render(request,'blog-single.html',context)
    except:
        messages.success(request, "Invalid Request")
        return redirect(reverse("list"))
    
# Blog Search View
def search(request):
    query=request.GET.get('query',None)
    blogs=Blog.objects.all()
    if query is not None:
        blogs=blogs.filter(
        Q(title__icontains=query)|
        Q(description__icontains=query)|
        Q(author__username__icontains=query)
        )
    paginator = Paginator(blogs ,10) # Shows only 10 records per page

    page = request.GET.get('page', 1)
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
    # If page is not an integer, deliver first page.
        blogs = paginator.page(1)
    except EmptyPage:
    # If page is out of range (e.g. 7777), deliver last page of results.
        blogs = paginator.page(paginator.num_pages)
    context={
        'blog_all_section': True,
        'search_section': True,
        'query' : query,
        'blogs':blogs
}

    return render(request,'blog-list-sidebar.html',context)

# Blog Post Reply View
@login_required
def ReplyPage(request,id, slug):
    comment=BlogComment.objects.get(id=id)
    form = Reply()
    if request.method == "GET":
        return redirect(reverse('detail', args = [slug]))
    if request.method=='POST':
        form = Reply(request.POST or None)
        if form.is_valid:
            new = form.save(commit=False)
            new.comment=comment
            new.save()
            form.save()
            return HttpResponseRedirect(reverse('detail', args = [slug]))
        else:
            return redirect(reverse('detail', args = [slug]))


# Blog  Post Form View
@login_required
def blogFormView(request):
    form = blogform()
    if request.method=='POST':
        form = blogform(request.POST ,  request.FILES)
        if form.is_valid():
            new = form.save(commit=False)
            new.author=request.user
            new.slug=slugify(new.title)
            new.save()
            form.save()
            return redirect('list')
    try:
        profile = UserProfile.objects.get(user = User.objects.get(username = request.user.username))
    except:
        profile = None
    context={
    'form':form,
    'blog_write':True,
    'profile' : profile
    }
    return render(request,'blogform.html',context)


# Self Blogs
@login_required
def self_Blogs(request):
    template_name="blog-list-sidebar.html"
    blog = Blog.objects.filter(author=User.objects.get(username=request.user.username))
    paginator = Paginator(blog ,10, allow_empty_first_page=True)
    page = request.GET.get('page', 1)
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage :
        blogs = paginator.page(paginator.num_pages)
    if request.user.is_authenticated:
        try:
            profile = UserProfile.objects.get(user = User.objects.get(username = request.user.username))
        except :
            profile = None
    else:
        profile = None
    context = {
        'blogs':blogs,
        'blog':blog,
        'self_blogs':True,
        'paginator': paginator,
        'profile':profile
    }
    return render(request,
                template_name,
                context
            )

# Blog Post Form View
@login_required
def blogFormViewEditing(request, blog_id):
    template_name="blogform_edit.html"
    try:
        obj = Blog.objects.get(id=blog_id, author = User.objects.get(username=request.user.username))
        if request.method!='POST':
            form = blogform(instance = obj)
        else:
            form = blogform(request.POST, request.FILES, instance = obj)
            if form.is_valid():
                form.save()
                return redirect(reverse("detail", args=[obj.slug]))
        if request.user.is_authenticated:
            try:
                profile = UserProfile.objects.get(user = User.objects.get(username = request.user.username))
            except :
                profile = None
        else:
            profile = None
        context={
            'blog_write':True,
            'form' : form,
            'obj': obj,
            'profile' : profile
        }
        return render(request,
                    template_name,
                    context
                )
    except Exception as e:
        return redirect("list")

@login_required
def AssignBlog(request):
    try:
        profile = UserProfile.objects.get(user = User.objects.get(username = request.user.username))
        if profile.golbal_Admin == "True":
            template_name='assign-a-blog.html'
            form = AssignBlogForm()
            if request.user.is_authenticated:
                try:
                    profile = UserProfile.objects.get(user = User.objects.get(username = request.user.username))
                except :
                    profile = None
            else:
                profile = None
            if request.method=='POST':
                form = AssignBlogForm(request.POST ,  request.FILES)
                if form.is_valid():
                    new = form.save(commit=False)
                    new.slug=slugify(new.title)
                    new.save()
                    form.save()
                    current_site = get_current_site(request)
                    mail_subject = 'VoiceItOut Team.'
                    message = f"A blog has been assigned to '{new.author.email}' from Global Admin '{request.user.email}'"
                    message += "\nYou can check and edit the details of the blog by following the below link:\n"
                    build_link = str(request.scheme) + "://" + str(get_current_site(request).domain) + str(reverse("blog_editing", args=[new.id]))
                    message += "\n"
                    message += str(build_link)
                    email = EmailMessage(mail_subject, message, to=[new.author.email, request.user.email])
                    email.send()
                    return redirect('list')
            context={
            'profile':profile,
            'form':form,
            'assign_blog':True

            }
            return render(request, template_name, context)
        else:
            return redirect("list")
    except Exception as e:
        print(e)

blogs/templates/assign-a-blog.html
{% extends 'mysite/base.html' %}
{% load static getImageBanner %}

{% block title %}Voice It Out | Write A  Blog {% if search_section %} Search {% endif %}{% endblock %}

{% block content %}


<!--Page Title-->
<section class="page-banner">
    {% if request.user|getImageBanner %}
        <div class="image-layer" style="background-image:url('/media/{{ request.user|getImageBanner }}');"></div>
    
    {% else %}
    <div class="image-layer" style="background-image:url('{% static 'mysite/images/background/banner-image-5.jpg' %}');"></div>
    {% endif %}


    <div class="banner-inner">
        <div class="auto-container">
            <div class="inner-container clearfix">
                <h1>Blogs</h1>
                <div class="page-nav">
                    <ul class="bread-crumb clearfix">
                        <li><a href="{% url 'home_page' %}">Home</a></li>
                        <li><a href="{% url 'list' %}">Blogs</a></li>
                        <li class="active">Assign A Blog</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>




<div class="sidebar-page-container">
    <div class="auto-container">
        <div class="row clearfix">


            <div class="content-side col-lg-8 col-md-12 col-sm-12">
                <div class="content-inner">
    
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
          There is error in  {{ field.name }} &nbsp;&nbsp;&nbsp; <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% endif %}
    <form method="POST" enctype='multipart/form-data' action="{% url 'Assign' %}">
        {% csrf_token %}
        
        <div class="card" style=" width: auto;">
                <div class="shadow p-3 bg-white rounded">

                    <div class="card-header text-center bg-transparent border-0">
                        <h3>
                               Assign A Blog
                        </h3>

                    </div>



                    <div class="card-body">
                           {% csrf_token %}
                           {{form.media}}

                            <div class="form-group">
                                 <label>Assign Author</label>
                                 <br>
                                {{ form.author }}

                            </div>
                           <div class="form-group">
                            <label>Title</label>
                            <input type="text" name="title"  maxlength="150" class="form-control" >
                        </div>
                        <div class="form-group">
                            <label>Image</label>
                            <input type="file" name="image"  maxlength="150" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Video</label>
                            <input type="text" name="video"  maxlength="150" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <textarea type="text" id="editor1" name="description"  maxlength="150" class="form-control"></textarea>
                        </div>
                     
                                       
                  
                            <input type="submit" class="btn btn-primary" value="Assign">
    
                       
                    </div>
                </div>
            </div>
        
     
      
       

    </form>
                    </div>
            </div>

    <div class="sidebar-side col-lg-4 col-md-12 col-sm-12">
        <aside class="sidebar">
            <div class="bg-layer">
                <div class="image-layer"
                    style="background-image:url('{% static 'mysite/images/background/sidebar-bg-image.jpg' %}');">
                </div>
            </div>

            <div class="sidebar-widget search-box">
                <div class="widget-inner">
                    <div class="sidebar-title">
                        <h4>Search</h4>
                    </div>
                    <form method="GET" action="{% url 'search' %}">

                        <div class="form-group">
                            <input type="search" name="query" autocomplete="off" placeholder="Keyword..."
                                value="{% if search_section %}{% if query %}{{ query }}{% endif %}{% endif %}">
                            <button type="submit"><span class="icon flaticon-magnifying-glass"></span></button>
                        </div>
                    </form>
                </div>
            </div>
            {% if request.user.is_authenticated %}
            <div class="sidebar-widget cat-widget">
                <div class="widget-content">
                    <div class="sidebar-title">
                        <h4>Self Blogs</h4>
                    </div>
                    <ul class="cat-links">
                        <li {% if blog_all_section %} class="current" {% endif %}><a href="{% url 'list' %}">All Blogs</a></li>
                        <li {% if self_blogs %} class="current" {% endif %}><a href="{% url 'self_blogs_url' %}">My Blogs</a></li>
                        {% if profile.golbal_Admin == "True" %}

                            <li {% if assign_blog %} class="current" {% endif %} ><a href="{% url 'Assign' %}">Assign A Bog</a></li>
                        {% endif %}
                       
                    </ul>
                </div>
            </div>
            {% endif %}

        </aside>
    </div>

    <br>
    <br>

</div>

</div>
</div>  


<script src="https://cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script>

<script>
    CKEDITOR.replace( 'editor1' );
</script>
<script>
    $(document).ready(function()
    {
        $("#id_author").addClass("form-control");
    })
</script>
{% endblock %}

blogs/templates/blog-list-sidebar.html
{% extends 'mysite/base.html' %}
{% load static getImageBanner social_share %}

{% block title %}

{% if blog_all_section %}
    Voice It Out | Blog {% if search_section %} Search {% endif %}
{% elif self_blogs %}
Voice It Out | User Blog {% if search_section %} Search {% endif %}
{% else %}
Voice It Out | Blog {% if search_section %} Search {% endif %}
{% endif %}
    {% endblock %}

{% block content %}

<!--Page Title-->
<section class="page-banner">
    
    
    {% if request.user|getImageBanner %}
        <div class="image-layer" style="background-image:url('/media/{{ request.user|getImageBanner }}');"></div>
    
    {% else %}
    <div class="image-layer" style="background-image:url('{% static 'mysite/images/background/banner-image-5.jpg' %}');"></div>
    {% endif %}

    <div class="banner-inner">
        <div class="auto-container">
            <div class="inner-container clearfix">
                <h1>Blogs</h1>
                <div class="page-nav">
                    <ul class="bread-crumb clearfix">
                        <li><a href="{% url 'home_page' %}">Home</a></li>
                        <li><a href="{% url 'blog' %}">Write A Blog</a></li>
                        <li class="active">Blog</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>


<div class="sidebar-page-container">
    <div class="auto-container">
        <div class="row clearfix">

            <!--Content Side-->
            <div class="content-side col-lg-8 col-md-12 col-sm-12">
                {% if search_section %}
                    {% if query %}
                        <div class="sec-title">
                            <h2>Search Results for "{{ query }}"</h2>
                        </div>
                    {% endif %}    
                {% endif %}    
                
                <div class="content-inner">
                    <div class="blog-posts">
                        <!--News Block Section-->
                        {% for blog in blogs %}
                        <div class="news-block-four">
                            <div class="inner-box">
                                <div class="image-box">
                                    <figure class="image"><img src="/media/{{ blog.image }}" alt=""></figure>
                                    <div class="date"><span>{{ blog.created_at|timesince }}</span></div>
                                    <div class="hover-box">
                                        
                                        {% if self_blogs %}
                                            <div class="more-link mb-5"><a href="{% url 'blog_editing' blog.id %}">Edit</a></div>
                                        {% endif %}
                                        <div class="more-link"><a href="{% url 'detail' blog.slug %}">Read More</a></div>
                                        
                                        
                                        
                                        
                                    </div>
                                </div>
                                <div class="lower-box">
                                    <div class="upper-info">
                                        <h2><a href="{% url 'detail' blog.slug %}">{{ blog.title|truncatechars:30 }}</a></h2>
                                        <div class="cat-info">
                                            <a href="#"><span class="fa fa-comment"></span>
                                                {% with total=blog.blogcomment_set.count %}
                                                {{ total }} Comment{{ total|default:1|pluralize }}
                                                {% endwith %}
                                            </a>
                                        </div>
                                    </div>
                                    <div class="text">{{ blog.description|striptags|truncatechars:100 }}</div>
                                    <div class="meta-info clearfix">
                                        <div class="author-info clearfix">
                                            <div class="author-icon"><span class="flaticon-user-3"></span></div>
                                            <div class="author-title">By {{ blog.author.username }}</div>
                                        </div>
                                        <div class="share-it">
                                            <a class="share-btn" href="#"><span class="icon flaticon-share"></span></a>
                                            <div class="share-list">
                                                <ul>
                                                    <li>{% post_to_facebook blog.get_absolute_url  '<span class="fab fa-facebook-f"></span>'  %}</li>
                                                    <li>{% post_to_twitter  blog.title blog.get_absolute_url  '<span class="fab fa-twitter"></span>'  %}</li>
                                                    <li>{% post_to_linkedin   blog.title blog.get_absolute_url  '<span class="fab fa-linkedin-in"></span>'  %}</li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <!-- End News Block Section -->
                    </div>
                    <!--Pagination-->
                    {% if blogs.has_other_pages %}
                        <div class="pagination-box text-center">
                                <ul class="styled-pagination">
                                {% if blogs.has_previous %}
                                    <li class="prev"><a href="?page={{ blogs.previous_page_number }}"><span class="icon flaticon-arrows-1"></span> Prev</a></li>
                                {% endif %}
                                {% for i in blogs.paginator.page_range %}
                                    {% if blogs.number == i %}
                                    <li class="active"><a href="?page={{ i }}" class="active">{{ i }}</a></li>
                                    {% else %}
                                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if blogs.has_next %}
                                    <li class="next"><a href="?page={{ blogs.next_page_number }}">Next <span class="icon flaticon-right-2"></span></a></li>
                                {% endif %}
                                </ul>
                                

                        </div>
                    {% endif %}
                    <!-- End Pagination -->
                </div>
            </div>

            <!--Sidebar Side-->
            <div class="sidebar-side col-lg-4 col-md-12 col-sm-12">
                <aside class="sidebar">
                    <div class="bg-layer">
                        <div class="image-layer"
                            style="background-image:url('{% static 'mysite/images/background/sidebar-bg-image.jpg' %}');">
                        </div>
                    </div>

                    <div class="sidebar-widget search-box">
                        <div class="widget-inner">
                            <div class="sidebar-title">
                                <h4>Search</h4>
                            </div>
                            <form method="GET" action="{% url 'search' %}">

                                <div class="form-group">
                                    <input type="search" name="query" autocomplete="off" placeholder="Keyword..."
                                        value="{% if search_section %}{% if query %}{{ query }}{% endif %}{% endif %}">
                                    <button type="submit"><span class="icon flaticon-magnifying-glass"></span></button>
                                </div>
                            </form>
                        </div>
                    </div>
                    {% if request.user.is_authenticated %}
                    <div class="sidebar-widget cat-widget">
                        <div class="widget-content">
                            <div class="sidebar-title">
                                <h4>Self Blogs</h4>
                            </div>
                            <ul class="cat-links">
                                <li {% if blog_all_section %} class="current" {% endif %}><a href="{% url 'list' %}">All Blogs</a></li>
                                <li {% if self_blogs %} class="current" {% endif %}><a href="{% url 'self_blogs_url' %}">My Blogs</a></li>
                                {% if profile.golbal_Admin == "True" %}

                                    <li ><a href="{% url 'Assign' %}">Assign A Bog</a></li>
                                {% endif %}
                               
                            </ul>
                        </div>
                    </div>
                    {% endif %}

                </aside>
            </div>

        </div>
    </div>
</div>

{% endblock %}